---
packages:
  - build-essential
  - libreadline-dev
  - unzip
  - ripgrep
  - vim
  - make
  - cmake
  - curl
  - btop
  - ca-certificates
  - tilix
  - mesa-utils
  - nvtop
  # - grub-customizer # For managing GRUB bootloader
  - libfuse2t64 # requires universe apt-repo `sudo add-apt-repository universe`
  - keychain
  - tree
  - apt-transport-https
  - xclip
