- name: get latest release of neovim (cached)
  ansible.builtin.include_role:
    name: github-release-cached
  vars:
    gh_user: neovim
    gh_repo: neovim


- name: get current version
  ansible.builtin.command:
    argv:
      - nvim
      - --version
  register: current_version
  ignore_errors: true
  changed_when: false
  check_mode: false

- name: extract version
  set_fact:
    current_version: "{{ current_version.stdout_lines[0] | regex_search('([0-9]+\\.[0-9]+\\.[0-9]+)', multiline=True) }}"
  check_mode: false
  when:
    - current_version is succeeded and current_version.stdout_lines is defined

- name: extract version
  set_fact:
    current_version: "v{{ current_version }}"
  check_mode: false

- name: Show current version
  debug:
    var: current_version
  when:
    - current_version.rc is not defined

- name: latest release
  debug:
    var: release.tag
  when: release is defined

- name: pinned version
  debug:
    var: neovim_pinned_version

- name: set version to install from release
  set_fact:
    version_to_install: "{{ release.tag }}"
  when:
    - neovim_pinned_version is not defined
    - release is defined


- name: set version to install from pin
  set_fact:
    version_to_install: "{{ neovim_pinned_version }}"
  when:
    - neovim_pinned_version is defined

- name: Show version to install
  debug:
    var: version_to_install
- name: Installed correct version
  debug:
    var: version_to_install != current_version


- name: install appimage
  get_url:
    url: "https://github.com/neovim/neovim/releases/download/{{ version_to_install }}/nvim-linux-{{ 'arm64' if ansible_facts['architecture'] == 'aarch64' else 'x86_64' }}.appimage"
    dest: "{{ ansible_facts['env']['HOME'] }}/.local/bin/nvim"
    mode: '0755'
    force: true
  when:
    - not ansible_check_mode
    - version_to_install | default('') | length > 0
    - version_to_install != current_version
