---
- hosts: localhost
  roles:
    - role: apt
      tags: [apt]
    - role: nvim
      tags: [nvim]
    - role: lua
      tags: [lua]
    - role: uv
      tags: [uv]
    - role: mise
      tags: [mise]
    - role: cargo
      tags: [cargo]
    - role: nerdfonts
      tags: [nerdfonts]
    - role: opencode
      tags: [opencode]
    - role: llama-cpp
      tags: [llama-cpp]
    - role: starship
      tags: [starship]
    - role: geerlingguy.docker
      tags: [docker]
      become: true
    - role: lemond
      tags: [lemond]
      become: true
    - role: openwebui
      tags: [openwebui]
      become: true
